### ISSUE TITLE
About Slate

### ISSUE THREAD

**Issue by unsanedingding** [arbonagw/AstralShipwright#1]
Thank you for your share :)
I have  two questions of  Slate
1. Slate can use to VR(3d scene)? 
2. If i have a lot of UI layout(Look and feel) config flie, and i load these config file at runtime, slate is my only choise? I guese maybe UMG is not  fit for me in this case.
Thank you.

**Comment by strangergwenn** [comment]
Hey, sorry for the delay - looks like I don't have notifications for bug reports somehow. This is more of a game project though, please dont use this for general Unreal questions! Try the Unreal Slackers Discord for help on Slate and UMG, I'm right there.
